# Generated by Django 3.2.24 on 2024-03-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
